name: chemvae
channels:
  - rdkit
  - conda-forge

dependencies:
  - keras=2.0.6
  - tensorflow
  - h5py
  - hdf5
  - pandas=1.1.5
  - python>3
  - scikit-learn=0.24.2
  - boost
  - rdkit=2020.09.1.0
  - yaml
  - numpy=1.19.2
  - matplotlib=3.3.4
  - bayesian-optimization=1.4.0
  - absl-py<2
  - ipython




