

universe = vanilla
log = logs/job_$(Cluster).log
error = logs/job_$(Cluster)_$(Process).err
output = logs/job_$(Cluster)_$(Process).out

executable = testing_env.sh
arguments = 

requirements = (OpSysMajorVer == 7 || OpSysMajorVer == 8) 

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = pipeline.tar.gz

request_cpus = 4
request_memory = 20GB
request_disk = 20GB

queue 1